### ISSUE TITLE
请问目前的这个开源是个什么东西？

### ISSUE THREAD

**Issue by HelplessMan** [simon-8/contract-center#4]
最开始关注的是作者的小说那套开源，然后说明了要重写。恰巧仓库是当前这个。今天看了下最近有更新打开一看有点懵逼，又是守护进程 又是签名 又是PDF。。话说这个到底是个什么样子的CMS。感觉和作者以前说的小说有点不沾边了.... 还是说某个CMS么。。。

**Comment by simon-8** [comment]
这个项目的初衷是用laravel做一个简易的管理后台, 目前还没做完.
dev分支是基于master分支做的一些个人的东西, 让你有些误解, 不好意思.
